name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Nerdbank.GitVersioning
      run: dotnet tool install -g nbgv
    - name: Version
      id: version
      run: echo "::set-output name=version::$(nbgv get-version -v SemVer2)"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build ./Parithon.StreamDeck.SDK.Core --no-restore --configuration Release --nologo
        dotnet build ./Parithon.StreamDeck.SDK.MSBuild.Tool --no-restore --configuration Release --nologo
        dotnet build ./Parithon.StreamDeck.SDK.MSBuild --no-restore --configuration Release --nologo
        dotnet build ./Parithon.StreamDeck.SDK --no-restore --configuration Release --nologo
    - name: Pack
      run: |
        dotnet pack ./Parithon.StreamDeck.SDK.Core --no-restore --configuration Release
        dotnet pack ./Parithon.StreamDeck.SDK.MSBuild --no-restore --configuration Release
        dotnet pack ./Parithon.StreamDeck.SDK --no-restore --configuration Release
    - name: Upload CORE package
      uses: actions/upload-artifact@v2
      with:
        name: corepkg
        path: "./nupkgs/Parithon.StreamDeck.SDK.Core.${{ steps.version.outputs.version }}.nupkg"
    - name: Upload MSBUILD package
      uses: actions/upload-artifact@v2
      with:
        name: msbuildpkg
        path: "./nupkgs/Parithon.StreamDeck.SDK.MSBuild.${{ steps.version.outputs.version }}.nupkg"
    - name: Upload SDK package
      uses: actions/upload-artifact@v2
      with:
        name: sdkpkg
        path: "./nupkgs/Parithon.StreamDeck.SDK.${{ steps.version.outputs.version }}.nupkg"
        
    outputs:
      version: ${{ steps.version.outputs.version }}
