name: Pull Request Check

on:
  pull_request:
    branches-ignore: [ main, develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Invalid Base Location
      if: github.pull_request.base.ref == 'main'
      run: echo 1
